aichaos/rivescript-js

src/brain.coffee
src/utils.coffee

relates to a post https://www.chatbots.org/ai_zone/viewthread/2314/ 
Rivescript doesn’t cut the trailing blanks after cleaning punctuation symbols and leading blanks give also problems; 
for example, with :
+ do you love me
- yes, i do !
if user enter : 
do you love me ? (with a blank before ? ), this doesn’t match 
do you love me?  works well 
do you love me? doesn’t match
I add this branch to add the trim once punctuation has been treated. 
Everything comes back to : do you love me  and is ok.
-> as this is my first Coffee script, my first github pull and my first rivescript test, be indulgent !
HTH

trim user's sentence

---

eg/web-client/chat.html
src/lang/javascript.coffee
test/test-rivescript.coffee

Hello Noah,
This adds support for passing actual js functions to **setSubroutine** (as opposed to just strings). We are building a set of extensions for rivescript to leverage certain components in our system and I found this feature useful for several reasons:
- taking advantage of closures to reference our components
- better tooling support (write js with syntax coloring and all that jazz)
- support for transpilers (we run on babel so it's nice to be able to write the same flavor of js in subroutines as well)

Allow using actual js functions in Rivescript.setSubroutine

---

src/parser.coffee
src/rivescript.coffee
test/test-rivescript.coffee

This add ability to output object macros in `stringify()`. Pull request includes test to validate output matches expected string.
Hoping this passes muster and is merged in quickly. This is necessary for a project that requires validating and syncing compiled Rive files for access and reading by multiple Rive workers.
(Loving Rivescript btw!)

Include objects macros in output of deparse and stringify.

---

package.json
src/rivescript.coffee
test/fixtures/recursive/test.rive
test/fixtures/test.rive
test/test-rivescript.coffee

`loadDirectory()` should allow for recursive lookup of Rivescript files inside a directory with child directories. 
Pull request includes update to loadDirectory() and a test case ensuring that Rivescript files in child directories are also located and parsed.
For our large project, it is easier for our editors to manage smaller files organized in subdirectories inside our main language directory. NodeJS's standard readdir is a bit lacking in ability to dive into child directories.
It does use the `fs-readdir-recursive` module, which while I would have preferred to not require an additional module, it does make the overall functionality of `loadDirectory()` better.

Allow loadDirectory() to recursively load files.

---

src/brain.coffee

```@master._sorted.thats[top]``` returns an array hence this was always evaluated to true.

check array length when looking for previous

---

src/brain.coffee

This replaces direct references to vars in Brain by using **setUservar** and **getUservar**. This is practical for cases when people choose to override setUservar/getUservar behavior in the RiveScript class

Replace var set/get with brain var methods

---

src/brain.coffee
test/test-rivescript.coffee

this is a fix for #88. includes tests across all three available concat methods (none, space, newline)

allow * condition to respect ^ continue concat format

---

src/parser.coffee
test/test-objects.coffee
test/test-options.coffee

Newlines in replies need to be escaped so that they do not render as actual newlines in stringify() output.
Without it, newlines will cause output to be invalid, for example:
```
! version = 2.0
! local concat = none
+ hello
- Hi!
Nice to meet you.
```
when it should correctly output:
```
! version = 2.0
! local concat = none
+ hello
- Hi!\nNice to meet you.
```
Includes tests. Also trims extra whitespace outputted after `> topic name `.

Escape newlines in stringify()

---

src/brain.coffee
test/test-rivescript.coffee

Do not allow redirects to be blank if `<star>`, `<bot>`, `<get>` returns an undefined string.
See issue #92 for further details.

<@> redirect does not work if <star> is undefined

---

src/parser.coffee
test/test-options.coffee

In my haste to get newlines fixed in stringify(), i missed escapeing newlines for when ^ continue used in conditionals that when concat is newline.
corrected, with tests.

also escape newlines when used with conditionals. updated tests.

---

src/brain.coffee
src/parser.coffee
test/test-triggers.coffee

This pull requests fixes #100, which is for when empty entities exist in array, alternations, or optionals. Previously, having an empty entity would cause matching issues that would essentially match on any given case. This will now filter out known empty entities in triggers, previous and array variables.
PR also includes validation warnings for when arrays, alternations, or optionals contain empty entities in beginning, middle, or end. 
Tests for both filtering and proper validation warnings are included with this request.

Piped array with a blank ending causes matching errors

---

docs/html/utils.html
docs/utils.md
src/brain.coffee
src/utils.coffee

Per issue #108, if you used a line break sequence "\n" inside a `<call>` tag, it would break the regular expression trying to match the `<call>...</call>` sequence because this regexp couldn't handle line breaks.
JavaScript regexp doesn't support the `/.../s` flag which would make the `.` metacharacter match line break characters. The workaround is to replace the `.` metacharacter with the sequence `[\s\S]` to match spaces and non-space characters (essentially forcing it to match everything, including line breaks).
```diff
- callRe = /<call>(.+?)<\/call>/ig
+ callRe = /<call>([\s\S]+?)<\/call>/ig
```
Additionally, I changed the code to call the new `utils.trim()` function (which is a more compatible version of `String.prototype.trim()` to support Internet Explorer < 9) instead of the …

Fix line breaks ruining call tag regexp

---

docs/html/rivescript.html
docs/rivescript.md
eg/json-server/README.md
eg/persistence/README.md
src/brain.coffee
src/rivescript.coffee
test/test-rivescript.coffee

Adding initialMatch() and `__initialmatch__` features too track the initial trigger that the brain evaluated. Unlike `__lastmatch__`, `__initialmatch__` will only be set on the first evaluation and not change on subsequent redirects. `__initialmatch__` will reset on each reply() or replyAsync() request.
This PR includes a initialMatch() function to easily fetch the value of `__initialmatch__`.
Includes passing tests and updated docs. (And is current w/ upstream!)

Add `initialMatch()` feature

---

Changes.md
src/brain.coffee
test/test-unicode.coffee

This fixes #118 by changing the `[A-Za-z]+` regexp to `[^\s\d]+` to match all Unicode letters while still excluding numbers and spaces (as was the original intention of the `_` wildcard).

Fix underscore wildcards not matching Unicode letters

---

eg/README.md
eg/router/README.md
eg/router/controllers.js
eg/router/router.js

The discussion in #130 of using RiveScript as a router-controller system was somewhat interesting and I wrote an example bot that demonstrates how someone could set up such a system using RiveScript.
This adds `eg/router` to the list of examples.

Add a router example

---

src/brain.coffee
test/test-rivescript.coffee

In the case of `__history__` being invalidly set (through settings via `setUservar()`), ensure that `input` and `reply` arrays are set if they do not exist, and that a fallback undefined string is given when requesting `__history__.input[0]` and `__history__.reply[0]` when creating `<input>` and `<reply>` tags.
Example situation:
```
// Set an invalid history
rs.setUservar(userId, "__history__", {"input": ["Hi"], "reply": []});
// Generate response
rs.reply(userId, "Bye");
```
Error generated:
`TypeError: Cannot read property '0' of undefined at Brain.processTags (./node_modules/rivescript/lib/brain.js:663:82)`
A passing test is also provided.

Prevent errors if history object is invalid

---

Changes.md
README.md
docs/html/rivescript.html
docs/rivescript.md
package.json
src/brain.coffee
src/parser.coffee
src/rivescript.coffee
test/test-options.coffee
test/test-replies.coffee

This knocks out various small annoying bugs and adds some quality-of-life features.
This fixes a common annoying bug where an `{@redirect}` would fail if the author included a space between the `@` and the trigger, for example `{@ hello}` vs. `{@hello}`.
The redirect text is stripped of whitespace before being looked up which resolves that issue.
Fixes #145 
Adds more documentation to the `rs.Promise` function, including a full example of how to use `replyAsync()` in conjunction with the object macro returning a promise.
Also adds a link to the RiveScript Playground on the main README file.
Fixes #144 
This is a quality-of-life improvement for RiveScript authors who find it difficult to write the word `i` in lowercase for the sake of triggers (e.g. `i am # years old`).
This adds a …

Misc low-hanging fruit, bug fixes and feature additions

---

.travis.yml
eg/brain/coffee.rive
rivescript.d.ts
shell.js
src/lang/coffee.coffee

@kirsle If you like and merge this I will make the same changes to `shell.coffee`

Shell: Add option to watch/reload the brain

---

src/brain.coffee
test/test-triggers.coffee

When an array reference is missing, trigger regexp compiles with a `||` that causes wildcard matches.
Fix strips out any double-pipes in trigger regexp before evaluation.
Tests included.

Prevent accidental double-piped wildcard caused by missing array.

---

src/brain.coffee
test/test-objects.coffee

This makes the regexp to substitute the intermediary "`{__call__}`" tags case-insensitively, to fix #178.
Using an object macro inside a text manipulation tag like `{uppercase}` in a BEGIN block still has more caveats (e.g.: the `{uppercase}` will uppercase the *name* of the object macro, and possibly give you an "[ERR: object not found]" error... but there's only so much I can do about that. Authors can work around it by defining their object macro under multiple names, like when using `setSubroutine`.

Case insensitive regexp for intermediate call tags

---

src/parser.coffee
test/test-triggers.coffee

This includes the current topic in some common errors from the parser. Examples:
```
Weird single-character line 'i' found (in topic random) at tmp/test.rive line 7
Unknown command '$' (in topic random) at tmp/test.rive line 8
```
The errors affected:
* Syntax errors.
* Weird single-character lines.
* Unknown command symbol.
Fixes #140

Include the topic in some common parser errors

---

src/inheritance.coffee
src/parser.coffee
src/rivescript.coffee
test/test-options.coffee

This change allows the `forceCase` option to work on topics, too: both on the `>topic` declaration line and on the `{topic=}` tag, for consistency/sanity. That fixes #158.
This also updates the "deep recursion while scanning topic inheritance" error to include the current topic it was looking at when it gave up the search, to fix #167.

Force case for topics, and better inheritance error

---

src/brain.coffee
src/inheritance.coffee
test/test-replies.coffee

This implements the fix to the `%Previous` sorting algorithm identified in [rivescript-python#60](https://github.com/aichaos/rivescript-python/pull/60).

Fix sorting algorithm for %Previous

---

src/brain.coffee
src/parser.coffee
test/test-objects.coffee

This change makes it possible to include **synchronous** object macro calls inside of redirects (both the command and inline form).
This fixes #201.
Example from the unit test:
```
> object echo javascript
var message = args.join(" ");
return message;
< object
+ hello bot
- Hello human.
+ redirect to *
@ <call>echo <star></call>
+ inline to *
- "<sentence>": {@ <call>echo <star></call>}
```
This is similar to the bug fix in #111 when object macros were fixed for conditional commands. It only supports **synchronous** macros (ones which return a string reply, *not* a promise) for the same reason.
In order to avoid regular expression problems with the `{@...}` syntax's curly brackets conflicting with those from the mangled `{__call_arg__}` types of tags, I changed the delimiter of the …

Allow synchronous call tags to work inside redirects

---

src/brain.coffee
src/rivescript.coffee
src/utils.coffee

It Makes a lot of less interactions when the number of subs is too large

New sub/person substitution algorithm. 

---

rivescript.d.ts
shell.js
src/parser.coffee
src/rivescript.coffee

Add ability to set a default (brain-wide) `concat` flag

---

package.json
src/rivescript.coffee

Hello Here,
I did removed the dependency on for the web environment. This is can be linked to issue #186.

Xml http request support

---

src/parser.coffee
test/test-unicode.coffee

This feature alleviates a huge pain point that a lot of users have experienced with Unicode keyword triggers.
* Fixes #147 
* Fixes #253 
* Fixes #254 
Users wanted to be able to write things like this in their RiveScript code:
```
// (this means "hello" in Chinese)
+ [*] 你好 [*]
- 你好!
```
The intention is that the word `你好` appearing _anywhere_ in a message should be able to match that trigger, as it does when using standard ASCII characters. However, the regexps that make "optional wildcards" like `[*]` work have problems matching against Unicode characters outside the ASCII range.
This adds a new `?Keyword` command to complement the `+Trigger` as a workaround for this very common use case:
```
? 你好
- 你好!
```
Under the hood, the `?Keyword` is re-written into a `+Trigger` which includes …

Add ?Keyword command to work around Unicode keyword bug

---

src/parser.coffee
src/utils.coffee

Escaping the underscore in JavaScript Regular Expressions is not necessary. 
This closes #250

Remove escaping underscores in Regular Expressions

---

rivescript.d.ts

Fixes https://github.com/aichaos/rivescript-js/issues/276
- makes callback parameters optional for `loadDirectory()` and `loadFile()`, and adds `Promise<any>` return types for the same
- adds optional `scope` parameter and a `Promise<string>` return type for `reply()`

Update TypeScript type definition file for v2.0.0 changes

---

rivescript.d.ts

This change updates the return types of certain functions to their current (v2.x) `Promise`-based implementation, and fills in some holes where there were no annotations previously. It also fixes the following TypeScript error:
```
ERROR in /Users/Foo/bar-app/node_modules/rivescript/rivescript.d.ts
83:2 An export assignment cannot be used in a module with other exported elements.
81 | 	}
82 |
> 83 | 	export = RiveScript;
| 	^
84 | }
85 |
```

TypeScript declaration file: Fix return types and export assignment

---

rivescript.d.ts

This one only shows up once you set the compiler to `"strict": true`! Missed it until now.

Proper types on Promise resolve/reject params

---

docs/brain.md
docs/rivescript.md
docs/sessions.md
package-lock.json
package.json
rivescript.d.ts
tsconfig.json

Hey! So, I found that a couple properties/methods I was trying to use in subroutines (public stuff) were not reflected in the type definition file. This PR adds a whole bunch of stuff to `rivescript.d.ts`, and fixes/adds to some method documentation (including explicitly mentioning when the resolved value of a promise is `void`—hope that's okay).
In the process, I added `typescript` to the `"devDependencies"` in `package.json`; I hope that's all right, too. I figured having it there for _development_ wouldn't be an issue, and it helps out with using the declaration file properly. I also added a basic `tsconfig.json` file (which I annotated so it would be more clear) in order to see error consistency in the `rivescript.d.ts` file when contributors are editing it. One of the nice side …

Flesh out TS declarations to properly reflect public interface

---

src/parser.js

Define 'key' inside the stringify function due to receiving 'key is not defined' error when bot contains variables.

Fix stringify: key is not defined when variables are present

---

README.md
package.json
shell.js

Following our discussion on #329, I made the interactive shell available as a command-line tool when installing rivescript-js via npm (there was actually very little change to make, only a few additions to package.json). I chose to call the associated command "riveshell", tell me if you'd prefer another name.
It can be called via `$ npx riveshell /path/to/brain` when the package is installed locally, or simply `$ riveshell /path/to/brain` when installed globally. I ensured that the command works properly both on macOS (bash) and Windows (cmd, powershell and git-bash).
I also updated the README.md file and the doc at the top of `shell.js` to reflect this new feature. I moved the "Installation" section of the README above the "Usage" section because I assume that people should already have …

Make interactive shell easily available when installing via npm

---

src/brain.js
test/test-objects.js

This PR includes the error message in the response when error is raised within an object macro.
When an error is raised in an object, the error message is included along with the default error response, e.g. `[ERR: Error when executing JavaScript object: TypeError]`. Very useful for debugging & testing!
However, when an error is raised in an async object macro, instead of returning the above default error reply, it only returns `[ERR: Error raised by object macro]`. Adding error message to follow similar pattern above.
Test added to cover this.
👉  Take note of the misspelling in the tests of `asyc` that was preventing await tests from running.

Include error message when error raised by object macro

---

src/brain.js
test/test-objects.js

closes https://github.com/aichaos/rivescript-js/issues/376

Fix nested macro calls, and ordering relative to set/get and other tags
